######################################################################
# Automatically generated by qmake (3.0) Mon Oct 3 10:51:33 2016
######################################################################

TEMPLATE = app
TARGET = gitim
INCLUDEPATH += .

QT += gui widgets

# Input
HEADERS += main.h
SOURCES += main.cpp

FORMS += \
    frame.ui
